#include "gles2_loader.h"
PFNGLGETSTRINGPROC detonate_es_glGetString = nullptr;
PFNGLACTIVETEXTUREPROC detonate_es_glActiveTexture = nullptr;
PFNGLATTACHSHADERPROC detonate_es_glAttachShader = nullptr;
PFNGLBINDBUFFERPROC detonate_es_glBindBuffer = nullptr;
PFNGLBINDFRAMEBUFFERPROC detonate_es_glBindFramebuffer = nullptr;
PFNGLBINDTEXTUREPROC detonate_es_glBindTexture = nullptr;
PFNGLBLENDEQUATIONPROC detonate_es_glBlendEquation = nullptr;
PFNGLBLENDEQUATIONSEPARATEPROC detonate_es_glBlendEquationSeparate = nullptr;
PFNGLBLENDFUNCSEPARATEPROC detonate_es_glBlendFuncSeparate = nullptr;
PFNGLBUFFERDATAPROC detonate_es_glBufferData = nullptr;
PFNGLBUFFERSUBDATAPROC detonate_es_glBufferSubData = nullptr;
PFNGLCLEARPROC detonate_es_glClear = nullptr;
PFNGLCLEARCOLORPROC detonate_es_glClearColor = nullptr;
PFNGLCOLORMASKPROC detonate_es_glColorMask = nullptr;
PFNGLCOMPILESHADERPROC detonate_es_glCompileShader = nullptr;
PFNGLCREATEPROGRAMPROC detonate_es_glCreateProgram = nullptr;
PFNGLCREATESHADERPROC detonate_es_glCreateShader = nullptr;
PFNGLDELETEBUFFERSPROC detonate_es_glDeleteBuffers = nullptr;
PFNGLDELETEPROGRAMPROC detonate_es_glDeleteProgram = nullptr;
PFNGLDELETESHADERPROC detonate_es_glDeleteShader = nullptr;
PFNGLDELETETEXTURESPROC detonate_es_glDeleteTextures = nullptr;
PFNGLDETACHSHADERPROC detonate_es_glDetachShader = nullptr;
PFNGLDISABLEPROC detonate_es_glDisable = nullptr;
PFNGLDISABLEVERTEXATTRIBARRAYPROC detonate_es_glDisableVertexAttribArray = nullptr;
PFNGLDRAWELEMENTSPROC detonate_es_glDrawElements = nullptr;
PFNGLENABLEPROC detonate_es_glEnable = nullptr;
PFNGLENABLEVERTEXATTRIBARRAYPROC detonate_es_glEnableVertexAttribArray = nullptr;
PFNGLGENBUFFERSPROC detonate_es_glGenBuffers = nullptr;
PFNGLGENTEXTURESPROC detonate_es_glGenTextures = nullptr;
PFNGLGETATTRIBLOCATIONPROC detonate_es_glGetAttribLocation = nullptr;
PFNGLGETERRORPROC detonate_es_glGetError = nullptr;
PFNGLGETINTEGERVPROC detonate_es_glGetIntegerv = nullptr;
PFNGLGETPROGRAMINFOLOGPROC detonate_es_glGetProgramInfoLog = nullptr;
PFNGLGETPROGRAMIVPROC detonate_es_glGetProgramiv = nullptr;
PFNGLGETSHADERINFOLOGPROC detonate_es_glGetShaderInfoLog = nullptr;
PFNGLGETSHADERIVPROC detonate_es_glGetShaderiv = nullptr;
PFNGLGETUNIFORMLOCATIONPROC detonate_es_glGetUniformLocation = nullptr;
PFNGLGETVERTEXATTRIBPOINTERVPROC detonate_es_glGetVertexAttribPointerv = nullptr;
PFNGLGETVERTEXATTRIBIVPROC detonate_es_glGetVertexAttribiv = nullptr;
PFNGLISENABLEDPROC detonate_es_glIsEnabled = nullptr;
PFNGLISPROGRAMPROC detonate_es_glIsProgram = nullptr;
PFNGLLINKPROGRAMPROC detonate_es_glLinkProgram = nullptr;
PFNGLPIXELSTOREIPROC detonate_es_glPixelStorei = nullptr;
PFNGLSCISSORPROC detonate_es_glScissor = nullptr;
PFNGLSHADERSOURCEPROC detonate_es_glShaderSource = nullptr;
PFNGLTEXIMAGE2DPROC detonate_es_glTexImage2D = nullptr;
PFNGLTEXPARAMETERIPROC detonate_es_glTexParameteri = nullptr;
PFNGLTEXSUBIMAGE2DPROC detonate_es_glTexSubImage2D = nullptr;
PFNGLUNIFORM1IPROC detonate_es_glUniform1i = nullptr;
PFNGLUNIFORMMATRIX4FVPROC detonate_es_glUniformMatrix4fv = nullptr;
PFNGLUSEPROGRAMPROC detonate_es_glUseProgram = nullptr;
PFNGLVERTEXATTRIBPOINTERPROC detonate_es_glVertexAttribPointer = nullptr;
PFNGLVIEWPORTPROC detonate_es_glViewport = nullptr;
bool detonate_gles2_resolve(retro_hw_get_proc_address_t proc)
{
    detonate_es_glGetString = reinterpret_cast<PFNGLGETSTRINGPROC>(proc("glGetString"));
    if (!detonate_es_glGetString) return false;
    detonate_es_glActiveTexture = reinterpret_cast<PFNGLACTIVETEXTUREPROC>(proc("glActiveTexture"));
    if (!detonate_es_glActiveTexture) return false;
    detonate_es_glAttachShader = reinterpret_cast<PFNGLATTACHSHADERPROC>(proc("glAttachShader"));
    if (!detonate_es_glAttachShader) return false;
    detonate_es_glBindBuffer = reinterpret_cast<PFNGLBINDBUFFERPROC>(proc("glBindBuffer"));
    if (!detonate_es_glBindBuffer) return false;
    detonate_es_glBindFramebuffer = reinterpret_cast<PFNGLBINDFRAMEBUFFERPROC>(proc("glBindFramebuffer"));
    if (!detonate_es_glBindFramebuffer) return false;
    detonate_es_glBindTexture = reinterpret_cast<PFNGLBINDTEXTUREPROC>(proc("glBindTexture"));
    if (!detonate_es_glBindTexture) return false;
    detonate_es_glBlendEquation = reinterpret_cast<PFNGLBLENDEQUATIONPROC>(proc("glBlendEquation"));
    if (!detonate_es_glBlendEquation) return false;
    detonate_es_glBlendEquationSeparate = reinterpret_cast<PFNGLBLENDEQUATIONSEPARATEPROC>(proc("glBlendEquationSeparate"));
    if (!detonate_es_glBlendEquationSeparate) return false;
    detonate_es_glBlendFuncSeparate = reinterpret_cast<PFNGLBLENDFUNCSEPARATEPROC>(proc("glBlendFuncSeparate"));
    if (!detonate_es_glBlendFuncSeparate) return false;
    detonate_es_glBufferData = reinterpret_cast<PFNGLBUFFERDATAPROC>(proc("glBufferData"));
    if (!detonate_es_glBufferData) return false;
    detonate_es_glBufferSubData = reinterpret_cast<PFNGLBUFFERSUBDATAPROC>(proc("glBufferSubData"));
    if (!detonate_es_glBufferSubData) return false;
    detonate_es_glClear = reinterpret_cast<PFNGLCLEARPROC>(proc("glClear"));
    if (!detonate_es_glClear) return false;
    detonate_es_glClearColor = reinterpret_cast<PFNGLCLEARCOLORPROC>(proc("glClearColor"));
    if (!detonate_es_glClearColor) return false;
    detonate_es_glColorMask = reinterpret_cast<PFNGLCOLORMASKPROC>(proc("glColorMask"));
    if (!detonate_es_glColorMask) return false;
    detonate_es_glCompileShader = reinterpret_cast<PFNGLCOMPILESHADERPROC>(proc("glCompileShader"));
    if (!detonate_es_glCompileShader) return false;
    detonate_es_glCreateProgram = reinterpret_cast<PFNGLCREATEPROGRAMPROC>(proc("glCreateProgram"));
    if (!detonate_es_glCreateProgram) return false;
    detonate_es_glCreateShader = reinterpret_cast<PFNGLCREATESHADERPROC>(proc("glCreateShader"));
    if (!detonate_es_glCreateShader) return false;
    detonate_es_glDeleteBuffers = reinterpret_cast<PFNGLDELETEBUFFERSPROC>(proc("glDeleteBuffers"));
    if (!detonate_es_glDeleteBuffers) return false;
    detonate_es_glDeleteProgram = reinterpret_cast<PFNGLDELETEPROGRAMPROC>(proc("glDeleteProgram"));
    if (!detonate_es_glDeleteProgram) return false;
    detonate_es_glDeleteShader = reinterpret_cast<PFNGLDELETESHADERPROC>(proc("glDeleteShader"));
    if (!detonate_es_glDeleteShader) return false;
    detonate_es_glDeleteTextures = reinterpret_cast<PFNGLDELETETEXTURESPROC>(proc("glDeleteTextures"));
    if (!detonate_es_glDeleteTextures) return false;
    detonate_es_glDetachShader = reinterpret_cast<PFNGLDETACHSHADERPROC>(proc("glDetachShader"));
    if (!detonate_es_glDetachShader) return false;
    detonate_es_glDisable = reinterpret_cast<PFNGLDISABLEPROC>(proc("glDisable"));
    if (!detonate_es_glDisable) return false;
    detonate_es_glDisableVertexAttribArray = reinterpret_cast<PFNGLDISABLEVERTEXATTRIBARRAYPROC>(proc("glDisableVertexAttribArray"));
    if (!detonate_es_glDisableVertexAttribArray) return false;
    detonate_es_glDrawElements = reinterpret_cast<PFNGLDRAWELEMENTSPROC>(proc("glDrawElements"));
    if (!detonate_es_glDrawElements) return false;
    detonate_es_glEnable = reinterpret_cast<PFNGLENABLEPROC>(proc("glEnable"));
    if (!detonate_es_glEnable) return false;
    detonate_es_glEnableVertexAttribArray = reinterpret_cast<PFNGLENABLEVERTEXATTRIBARRAYPROC>(proc("glEnableVertexAttribArray"));
    if (!detonate_es_glEnableVertexAttribArray) return false;
    detonate_es_glGenBuffers = reinterpret_cast<PFNGLGENBUFFERSPROC>(proc("glGenBuffers"));
    if (!detonate_es_glGenBuffers) return false;
    detonate_es_glGenTextures = reinterpret_cast<PFNGLGENTEXTURESPROC>(proc("glGenTextures"));
    if (!detonate_es_glGenTextures) return false;
    detonate_es_glGetAttribLocation = reinterpret_cast<PFNGLGETATTRIBLOCATIONPROC>(proc("glGetAttribLocation"));
    if (!detonate_es_glGetAttribLocation) return false;
    detonate_es_glGetError = reinterpret_cast<PFNGLGETERRORPROC>(proc("glGetError"));
    if (!detonate_es_glGetError) return false;
    detonate_es_glGetIntegerv = reinterpret_cast<PFNGLGETINTEGERVPROC>(proc("glGetIntegerv"));
    if (!detonate_es_glGetIntegerv) return false;
    detonate_es_glGetProgramInfoLog = reinterpret_cast<PFNGLGETPROGRAMINFOLOGPROC>(proc("glGetProgramInfoLog"));
    if (!detonate_es_glGetProgramInfoLog) return false;
    detonate_es_glGetProgramiv = reinterpret_cast<PFNGLGETPROGRAMIVPROC>(proc("glGetProgramiv"));
    if (!detonate_es_glGetProgramiv) return false;
    detonate_es_glGetShaderInfoLog = reinterpret_cast<PFNGLGETSHADERINFOLOGPROC>(proc("glGetShaderInfoLog"));
    if (!detonate_es_glGetShaderInfoLog) return false;
    detonate_es_glGetShaderiv = reinterpret_cast<PFNGLGETSHADERIVPROC>(proc("glGetShaderiv"));
    if (!detonate_es_glGetShaderiv) return false;
    detonate_es_glGetUniformLocation = reinterpret_cast<PFNGLGETUNIFORMLOCATIONPROC>(proc("glGetUniformLocation"));
    if (!detonate_es_glGetUniformLocation) return false;
    detonate_es_glGetVertexAttribPointerv = reinterpret_cast<PFNGLGETVERTEXATTRIBPOINTERVPROC>(proc("glGetVertexAttribPointerv"));
    if (!detonate_es_glGetVertexAttribPointerv) return false;
    detonate_es_glGetVertexAttribiv = reinterpret_cast<PFNGLGETVERTEXATTRIBIVPROC>(proc("glGetVertexAttribiv"));
    if (!detonate_es_glGetVertexAttribiv) return false;
    detonate_es_glIsEnabled = reinterpret_cast<PFNGLISENABLEDPROC>(proc("glIsEnabled"));
    if (!detonate_es_glIsEnabled) return false;
    detonate_es_glIsProgram = reinterpret_cast<PFNGLISPROGRAMPROC>(proc("glIsProgram"));
    if (!detonate_es_glIsProgram) return false;
    detonate_es_glLinkProgram = reinterpret_cast<PFNGLLINKPROGRAMPROC>(proc("glLinkProgram"));
    if (!detonate_es_glLinkProgram) return false;
    detonate_es_glPixelStorei = reinterpret_cast<PFNGLPIXELSTOREIPROC>(proc("glPixelStorei"));
    if (!detonate_es_glPixelStorei) return false;
    detonate_es_glScissor = reinterpret_cast<PFNGLSCISSORPROC>(proc("glScissor"));
    if (!detonate_es_glScissor) return false;
    detonate_es_glShaderSource = reinterpret_cast<PFNGLSHADERSOURCEPROC>(proc("glShaderSource"));
    if (!detonate_es_glShaderSource) return false;
    detonate_es_glTexImage2D = reinterpret_cast<PFNGLTEXIMAGE2DPROC>(proc("glTexImage2D"));
    if (!detonate_es_glTexImage2D) return false;
    detonate_es_glTexParameteri = reinterpret_cast<PFNGLTEXPARAMETERIPROC>(proc("glTexParameteri"));
    if (!detonate_es_glTexParameteri) return false;
    detonate_es_glTexSubImage2D = reinterpret_cast<PFNGLTEXSUBIMAGE2DPROC>(proc("glTexSubImage2D"));
    if (!detonate_es_glTexSubImage2D) return false;
    detonate_es_glUniform1i = reinterpret_cast<PFNGLUNIFORM1IPROC>(proc("glUniform1i"));
    if (!detonate_es_glUniform1i) return false;
    detonate_es_glUniformMatrix4fv = reinterpret_cast<PFNGLUNIFORMMATRIX4FVPROC>(proc("glUniformMatrix4fv"));
    if (!detonate_es_glUniformMatrix4fv) return false;
    detonate_es_glUseProgram = reinterpret_cast<PFNGLUSEPROGRAMPROC>(proc("glUseProgram"));
    if (!detonate_es_glUseProgram) return false;
    detonate_es_glVertexAttribPointer = reinterpret_cast<PFNGLVERTEXATTRIBPOINTERPROC>(proc("glVertexAttribPointer"));
    if (!detonate_es_glVertexAttribPointer) return false;
    detonate_es_glViewport = reinterpret_cast<PFNGLVIEWPORTPROC>(proc("glViewport"));
    if (!detonate_es_glViewport) return false;
    return true;
}
